import { useState, useRef, useEffect } from "react";
import { Palette, Copy, Pipette } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { ToolLayout } from "@/components/tools/ToolLayout";
import { getToolById } from "@/lib/tools-data";
import { toast } from "sonner";

const tool = getToolById("color-picker")!;

function hexToRgb(hex: string): { r: number; g: number; b: number } | null {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16),
      }
    : null;
}

function rgbToHsl(r: number, g: number, b: number): { h: number; s: number; l: number } {
  r /= 255;
  g /= 255;
  b /= 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;

  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r:
        h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
        break;
      case g:
        h = ((b - r) / d + 2) / 6;
        break;
      case b:
        h = ((r - g) / d + 4) / 6;
        break;
    }
  }

  return {
    h: Math.round(h * 360),
    s: Math.round(s * 100),
    l: Math.round(l * 100),
  };
}

function generatePalette(baseHex: string): string[] {
  const rgb = hexToRgb(baseHex);
  if (!rgb) return [];

  const hsl = rgbToHsl(rgb.r, rgb.g, rgb.b);
  const palette: string[] = [];

  // Generate 5 shades
  for (let i = 0; i < 5; i++) {
    const lightness = 90 - i * 20;
    palette.push(`hsl(${hsl.h}, ${hsl.s}%, ${lightness}%)`);
  }

  return palette;
}

export default function ColorPicker() {
  const [color, setColor] = useState("#6366f1");
  const [palette, setPalette] = useState<string[]>([]);

  const rgb = hexToRgb(color);
  const hsl = rgb ? rgbToHsl(rgb.r, rgb.g, rgb.b) : null;

  useEffect(() => {
    setPalette(generatePalette(color));
  }, [color]);

  const copyColor = async (value: string, format: string) => {
    await navigator.clipboard.writeText(value);
    toast.success(`${format} copied!`);
  };

  const seoContent = {
    description: "Pick colors, generate complementary palettes, and convert between HEX, RGB, and HSL formats. Free online color picker for designers and developers.",
    content: `
      <h3>Complete Color Tool</h3>
      <p>Our Color Picker & Palette Generator is a comprehensive tool for designers and developers. Pick any color, see it in multiple formats, and generate complementary color palettes instantly.</p>
      
      <h3>Multiple Color Formats</h3>
      <p>View your selected color in HEX, RGB, and HSL formats. Click any format to copy it to your clipboard, ready to paste into your CSS, design tool, or code editor.</p>
      
      <h3>Automatic Palette Generation</h3>
      <p>Generate a palette of shades based on your selected color. Perfect for creating consistent color schemes for your designs, from light tints to dark shades.</p>
      
      <h3>Perfect for Web Development</h3>
      <p>Get color values in the exact format you need. HEX codes for quick styling, RGB for CSS and JavaScript, and HSL for dynamic color manipulation.</p>
    `,
    keywords: ["color picker", "color palette", "hex to rgb", "rgb to hsl", "color converter", "color generator", "design tool"],
    faqs: [
      {
        question: "What's the difference between HEX, RGB, and HSL?",
        answer: "HEX is a 6-digit hexadecimal code (#RRGGBB). RGB uses decimal values for red, green, blue (0-255 each). HSL uses hue (0-360°), saturation, and lightness percentages.",
      },
      {
        question: "How is the palette generated?",
        answer: "The palette is generated by varying the lightness value in HSL color space while maintaining the same hue and saturation. This creates harmonious shades of your chosen color.",
      },
      {
        question: "Can I pick colors from an image?",
        answer: "This version uses a color input picker. For extracting colors from images, you can take a screenshot and use your browser's developer tools eyedropper.",
      },
    ],
    aboutTool: "The Color Picker & Palette Generator lets you select colors, view them in multiple formats (HEX, RGB, HSL), and generate complementary palettes. Copy any color value with one click for use in your projects.",
  };

  return (
    <ToolLayout tool={tool} seoContent={seoContent}>
      <div className="max-w-2xl mx-auto space-y-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Palette className="w-5 h-5" />
              Color Picker & Palette
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Color Picker */}
            <div className="flex items-center gap-4">
              <div className="relative">
                <input
                  type="color"
                  value={color}
                  onChange={(e) => setColor(e.target.value)}
                  className="w-24 h-24 rounded-lg cursor-pointer border-2 border-border"
                />
              </div>
              <div className="flex-1 space-y-2">
                <Label>HEX Color</Label>
                <div className="flex gap-2">
                  <Input
                    value={color.toUpperCase()}
                    onChange={(e) => {
                      const val = e.target.value;
                      if (/^#[0-9A-Fa-f]{0,6}$/.test(val)) {
                        setColor(val);
                      }
                    }}
                    className="font-mono"
                  />
                  <Button
                    variant="outline"
                    size="icon"
                    onClick={() => copyColor(color.toUpperCase(), "HEX")}
                  >
                    <Copy className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            </div>

            {/* Color Preview */}
            <div
              className="h-32 rounded-lg border-2"
              style={{ backgroundColor: color }}
            />

            {/* Color Formats */}
            {rgb && hsl && (
              <div className="grid grid-cols-3 gap-4">
                <div className="space-y-2">
                  <Label>HEX</Label>
                  <Button
                    variant="outline"
                    className="w-full font-mono justify-between"
                    onClick={() => copyColor(color.toUpperCase(), "HEX")}
                  >
                    {color.toUpperCase()}
                    <Copy className="w-4 h-4" />
                  </Button>
                </div>
                <div className="space-y-2">
                  <Label>RGB</Label>
                  <Button
                    variant="outline"
                    className="w-full font-mono justify-between text-xs"
                    onClick={() => copyColor(`rgb(${rgb.r}, ${rgb.g}, ${rgb.b})`, "RGB")}
                  >
                    rgb({rgb.r}, {rgb.g}, {rgb.b})
                    <Copy className="w-4 h-4" />
                  </Button>
                </div>
                <div className="space-y-2">
                  <Label>HSL</Label>
                  <Button
                    variant="outline"
                    className="w-full font-mono justify-between text-xs"
                    onClick={() => copyColor(`hsl(${hsl.h}, ${hsl.s}%, ${hsl.l}%)`, "HSL")}
                  >
                    hsl({hsl.h}, {hsl.s}%, {hsl.l}%)
                    <Copy className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            )}

            {/* Generated Palette */}
            <div className="space-y-2">
              <Label>Generated Palette</Label>
              <div className="flex rounded-lg overflow-hidden">
                {palette.map((shade, i) => (
                  <button
                    key={i}
                    className="flex-1 h-16 transition-transform hover:scale-105"
                    style={{ backgroundColor: shade }}
                    onClick={() => copyColor(shade, "Color")}
                    title={shade}
                  />
                ))}
              </div>
              <p className="text-sm text-muted-foreground">Click any shade to copy</p>
            </div>
          </CardContent>
        </Card>
      </div>
    </ToolLayout>
  );
}
