import { Layout } from "@/components/layout/Layout";
import { motion } from "framer-motion";

export default function Terms() {
  return (
    <Layout>
      <section className="py-16 md:py-24">
        <div className="container mx-auto px-4 max-w-4xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
          >
            <h1 className="text-4xl md:text-5xl font-bold mb-8">Terms of Service</h1>
            <p className="text-muted-foreground mb-8">Last updated: February 6, 2025</p>

            <div className="prose prose-invert max-w-none space-y-8">
              <section>
                <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
                <p className="text-muted-foreground leading-relaxed">
                  By accessing and using ToolSuiteX, you accept and agree to be bound by these Terms of Service. 
                  If you do not agree to these terms, please do not use our services.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
                <p className="text-muted-foreground leading-relaxed">
                  ToolSuiteX provides a collection of free, browser-based tools including but not limited to: 
                  document generators, image editors, security utilities, developer tools, and content creation tools. 
                  All tools operate client-side unless otherwise specified.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">3. Free to Use</h2>
                <p className="text-muted-foreground leading-relaxed">
                  All tools on ToolSuiteX are provided free of charge. We do not require registration, 
                  subscription, or payment to access any of our features.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">4. User Responsibilities</h2>
                <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                  <li>Use the tools for lawful purposes only</li>
                  <li>Do not attempt to exploit, hack, or overload our services</li>
                  <li>Do not use our tools to create harmful, illegal, or offensive content</li>
                  <li>Respect intellectual property rights when using our tools</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">5. Intellectual Property</h2>
                <p className="text-muted-foreground leading-relaxed">
                  The ToolSuiteX brand, logo, and website design are our intellectual property. 
                  Content you create using our tools belongs to you. You may use, share, and modify 
                  any output generated by our tools without restriction.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">6. Disclaimer of Warranties</h2>
                <p className="text-muted-foreground leading-relaxed">
                  Our services are provided "as is" without warranties of any kind. We do not guarantee 
                  that our tools will be error-free, uninterrupted, or meet your specific requirements. 
                  Use our tools at your own risk.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">7. Limitation of Liability</h2>
                <p className="text-muted-foreground leading-relaxed">
                  ToolSuiteX shall not be liable for any direct, indirect, incidental, or consequential 
                  damages arising from your use of our services. This includes but is not limited to 
                  data loss, business interruption, or financial losses.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">8. Privacy</h2>
                <p className="text-muted-foreground leading-relaxed">
                  Your privacy is important to us. Please review our{" "}
                  <a href="/privacy" className="text-primary hover:underline">Privacy Policy</a>{" "}
                  to understand how we handle your data (spoiler: we don't collect it).
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">9. Changes to Terms</h2>
                <p className="text-muted-foreground leading-relaxed">
                  We reserve the right to modify these terms at any time. Continued use of our services 
                  after changes constitutes acceptance of the new terms.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">10. Contact</h2>
                <p className="text-muted-foreground leading-relaxed">
                  For questions about these Terms of Service, contact us at{" "}
                  <a href="mailto:sctv77834@gmail.com" className="text-primary hover:underline">
                    sctv77834@gmail.com
                  </a>
                </p>
              </section>
            </div>
          </motion.div>
        </div>
      </section>
    </Layout>
  );
}
